apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/trusted-service

patches:

  - target:
      version: v1
      kind: Ingress
      name: trusted-service-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: app.staging.bnetd.ci

  - target:
      version: v1
      kind: Ingress
      name: trusted-service-global-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app-global.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: app-global.staging.bnetd.ci

  - target:
      version: v1
      kind: Deployment
      name: trusted-service-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/safy-io/safy/safy-trusted-service:master
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_TEMP_BUCKET
          value: safy-trusted-svc-temp
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_PERSISTENT_BUCKET
          value: safy-trusted-svc-app
