apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ejbca-vaultsecret
spec:
  keys:
    - DB_PASSWORD
    - HSM_USER
    - HSM_PASSWORD
    - PASSWORD_ENCRYPTION_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
  path: internal/ejbca/app-env
  type: Opaque
