apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ejbca-vaultsecret
spec:
  keys:
    - EJBCA_BACKUP_S3_ACCESS_KEY_ID
    - EJBCA_BACKUP_S3_SECRET_ACCESS_KEY
    - EJBCA_DB_PASSWORD
    - EJBCA_DB_USER
    - EJBCA_PASSWORD_ENCRYPTION_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
  path: internal/ejbca/app-env
  type: Opaque
