apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca-deployment
  labels:
    app: ejbca
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ejbca
  template:
    metadata:
      labels:
        app: ejbca
    spec:
      containers:
      - name: ejbca
        image: keyfactor/ejbca-ce:8.3.2
        imagePullPolicy: Always
        
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 2Gi
        
        ports:
        - containerPort: 8081
          name: proxied-http
        - containerPort: 8082
          name: proxied-https
        
        env:
        - name: PROXY_HTTP_BIND
          value: "0.0.0.0"
        - name: TLS_SETUP_ENABLED
          value: later
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: ejbca-vaultsecret
              key: DB_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ejbca-vaultsecret
              key: DB_PASSWORD
        - name: PASSWORD_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: ejbca-vaultsecret
              key: PASSWORD_ENCRYPTION_KEY        
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: ejbca-vaultsecret
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ejbca-vaultsecret
              key: SMTP_PASSWORD

        startupProbe:
          httpGet:
            path: /ejbca/publicweb/healthcheck/ejbcahealth
            port: proxied-http
          timeoutSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /ejbca/publicweb/healthcheck/ejbcahealth
            port: proxied-http
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ejbca/publicweb/healthcheck/ejbcahealth
            port: proxied-http
          timeoutSeconds: 5
          failureThreshold: 1
      
        volumeMounts: []

      volumes: []
