apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: keycloak-

resources:
  - ../../cnpg-with-minio

patches:

  - target:
      version: v1
      kind: Deployment
      name: minio-deployment
    patch: |-
      - op: replace
        path: /metadata/labels/app
        value: keycloak-postgresql-backup-minio
      - op: replace
        path: /spec/selector/matchLabels/app
        value: keycloak-postgresql-backup-minio
      - op: replace
        path: /spec/template/metadata/labels/app
        value: keycloak-postgresql-backup-minio
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: KEYCLOAK_BACKUP_S3_ACCESS_KEY_ID
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: KEYCLOAK_BACKUP_S3_SECRET_ACCESS_KEY
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: keycloak-postgresql-backup-minio-pvc

  - target:
      version: v1
      kind: Service
      name: minio-service
    patch: |-
      - op: replace
        path: /spec/selector/app
        value: keycloak-postgresql-backup-minio

  - target:
      version: v1
      kind: Ingress
      name: minio-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: keycloak-postgresql-backup-minio-service
      - op: replace
        path: /spec/rules/0/host
        value: keycloak-postgresql-backup-minio.bpsusine.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: keycloak-postgresql-backup-minio.bpsusine.com
      - op: replace
        path: /spec/tls/0/secretName
        value: keycloak-postgresql-backup-minio-cert

  - target:
      version: v1alpha1
      kind: VaultSecret
      name: postgresql-vaultsecret
    patch: |-
      - op: replace
        path: /spec/keys
        value: [KEYCLOAK_DB_PASSWORD]
      - op: replace
        path: /spec/templates/password
        value: "{% .Secrets.KEYCLOAK_DB_PASSWORD %}"

  - target:
      version: v1
      kind: Cluster
      name: postgresql
    patch: |-
      - op: replace
        path: /spec/backup/barmanObjectStore/endpointURL
        value: http://keycloak-postgresql-backup-minio-service:9000
      - op: replace
        path: /spec/managed/roles/0/passwordSecret/name
        value: keycloak-postgresql-vaultsecret
      - op: replace
        path: /spec/backup/barmanObjectStore/s3Credentials/accessKeyId/key
        value: KEYCLOAK_BACKUP_S3_ACCESS_KEY_ID
      - op: replace
        path: /spec/backup/barmanObjectStore/s3Credentials/secretAccessKey/key
        value: KEYCLOAK_BACKUP_S3_SECRET_ACCESS_KEY

  - target:
      version: v1
      kind: ScheduledBackup
      name: postgresql-scheduledbackup
    patch: |-
      - op: replace
        path: /spec/cluster/name
        value: keycloak-postgresql
