apiVersion: apps/v1
kind: Deployment
metadata:
  name: safy-trusted-service-deployment
  labels:
    app: safy-trusted-service
spec:
  selector:
    matchLabels:
      app: safy-trusted-service
  template:
    metadata:
      labels:
        app: safy-trusted-service
    spec:
      containers:
      - name: application
        image: ghcr.io/safy-io/safy/safy-trusted-service:master
        imagePullPolicy: Always

        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 2Gi

        env:
        - name: CMP_URL
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: CMP_URL
        - name: CMP_HMAC_SECRET
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: CMP_HMAC_SECRET
        - name: ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: ROOT_PASSWORD
        - name: POSTGRESQL_DATABASE
          value: safy_db
        - name: POSTGRESQL_USER
          value: safy_user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: DB_PASSWORD
        - name: POSTGRESQL_PARAMETERS
          value: ?ssl=true&sslmode=require&preparedStatementCacheQueries=0
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: S3_SECRET_ACCESS_KEY
        - name: SMTP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: SMTP_ADDRESS
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: SMTP_PORT
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: SMTP_USER
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: SMTP_PASSWORD
        - name: SMTP_START_TLS
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: SMTP_START_TLS
        - name: TRUSTED_SERVICE_LICENSE
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: TRUSTED_SERVICE_LICENSE
        - name: TWILIO_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: TWILIO_ACCOUNT
        - name: TWILIO_API_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: TWILIO_API_KEY_SECRET
        - name: TWILIO_API_KEY_SID
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: TWILIO_API_KEY_SID
        - name: TWILIO_SMS_SENDER_PHONE
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: TWILIO_SMS_SENDER_PHONE
        - name: TWILIO_WHATSAPP_SENDER_PHONE
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: TWILIO_WHATSAPP_SENDER_PHONE

        ports:
        - name: http
          containerPort: 8789
          protocol: TCP
        
        startupProbe:
          httpGet:
            path: /api/health
            port: http
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          failureThreshold: 1
      
        volumeMounts: []

      volumes: []
