apiVersion: apps/v1
kind: Deployment
metadata:
  name: safy-trusted-service-deployment
  labels:
    app: safy-trusted-service
spec:
  selector:
    matchLabels:
      app: safy-trusted-service
  template:
    metadata:
      labels:
        app: safy-trusted-service
    spec:
      containers:
      - name: application
        image: ghcr.io/safy-io/safy/safy-trusted-service:master
        imagePullPolicy: Always

        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 2Gi

        env:
        - name: POSTGRESQL_DATABASE
          value: safy_db
        - name: POSTGRESQL_USER
          value: safy_user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: DB_PASSWORD
        - name: POSTGRESQL_PARAMETERS
          value: ?ssl=true&sslmode=require&preparedStatementCacheQueries=0
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: S3_SECRET_ACCESS_KEY

        ports:
        - name: http
          containerPort: 8789
          protocol: TCP
        
        startupProbe:
          httpGet:
            path: /api/health
            port: http
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          failureThreshold: 1
