apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: safy-vaultsecret
spec:
  keys:
    - CMP_HMAC_SECRET
    - CMP_URL
    - DEFAULT_SECRET_KEY
    - S3_ACCESS_KEY_ID
    - S3_SECRET_ACCESS_KEY
    - SMTP_ADDRESS
    - SMTP_PASSWORD
    - SMTP_PORT
    - SMTP_START_TLS
    - SMTP_USER
    - TRUSTED_SERVICE_BACKUP_S3_ACCESS_KEY_ID
    - TRUSTED_SERVICE_BACKUP_S3_SECRET_ACCESS_KEY
    - TRUSTED_SERVICE_DB_NAME
    - TRUSTED_SERVICE_DB_PASSWORD
    - TRUSTED_SERVICE_DB_USER
    - TRUSTED_SERVICE_ROOT_PASSWORD
    - TWILIO_ACCOUNT
    - TWILIO_API_KEY_SECRET
    - TWILIO_API_KEY_SID
    - TWILIO_SMS_SENDER_PHONE
    - TWILIO_WHATSAPP_SENDER_PHONE
  path: internal/safy/app-env
  type: Opaque
