apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: safy-vaultsecret
spec:
  keys:
    - CMP_URL
    - CMP_HMAC_SECRET
    - DB_NAME
    - DB_PASSWORD
    - DB_USER
    - DEFAULT_SECRET_KEY
    - DOCUMENT_SERVICE_LICENSE
    - ROOT_PASSWORD
    - S3_ACCESS_KEY_ID
    - S3_SECRET_ACCESS_KEY
    - SMTP_ADDRESS
    - SMTP_PORT
    - SMTP_USER
    - SMTP_PASSWORD
    - SMTP_START_TLS
    - TWILIO_ACCOUNT
    - TWILIO_API_KEY_SECRET
    - TWILIO_API_KEY_SID
    - TWILIO_SMS_SENDER_PHONE
    - TWILIO_WHATSAPP_SENDER_PHONE
  path: internal/safy/app-env
  type: Opaque
