apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: postgresql-vaultsecret
spec:
  keys:
    - DB_PASSWORD
  path: internal/safy/env
  templates:
    username: postgresql_user
    password: "{% .Secrets.DB_PASSWORD %}"
  type: Opaque
