apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: postgresql_db
      owner: postgresql_user
  #   recovery:
  #     source: abcd-postgresql
  #     recoveryTarget:
  #       targetTime: "2023-04-21 15:31:00+00:00"
  # externalClusters:
  #   - name: abcd-postgresql
  #     barmanObjectStore:
  #       destinationPath: s3://app/pg-backup
  #       endpointURL: http://abcd-postgresql-backup-minio-service:9000
  #       s3Credentials:
  #         accessKeyId:
  #           name: safy-vaultsecret
  #           key: ABCD_POSTGRESQL_BACKUP_S3_ACCESS_KEY_ID
  #         secretAccessKey:
  #           name: safy-vaultsecret
  #           key: ABCD_POSTGRESQL_BACKUP_S3_SECRET_ACCESS_KEY
  #       wal:
  #         compression: gzip
  #       data:
  #         compression: gzip
  managed:
    roles:
    - name: postgresql_user
      login: true
      superuser: false
      passwordSecret:
        name: postgresql-vaultsecret
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://app/postgresql-backup
      endpointURL: http://postgresql-backup-minio-service:9000
      s3Credentials:
        accessKeyId:
          name: safy-vaultsecret
          key: POSTGRESQL_BACKUP_S3_ACCESS_KEY_ID
        secretAccessKey:
          name: safy-vaultsecret
          key: POSTGRESQL_BACKUP_S3_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
