apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-tls-secret: default/admin-ca-config
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
spec:
  rules:
    - host: minio.bpsusine.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-service
                port:
                  name: console
  tls:
    - hosts:
        - minio.bpsusine.com
      secretName: minio-cert
