apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: keycloak-vaultsecret
spec:
  keys:
    - KEYCLOAK_ADMIN_PASSWORD
    - KEYCLOAK_BACKUP_S3_ACCESS_KEY_ID
    - KEYCLOAK_BACKUP_S3_SECRET_ACCESS_KEY
    - KEYCLOAK_DB_PASSWORD
    - KEYCLOAK_DB_USER
  path: internal/keycloak/app-env
  type: Opaque
