apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: keycloak-vaultsecret
spec:
  keys:
    - ADMIN_PASSWORD
    - DB_PASSWORD
    - DB_USER
  path: internal/keycloak/app-env
  type: Opaque
