apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service-deployment
  labels:
    app: document-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
      - name: application
        image: ghcr.io/safy-io/safy/safy-document-service:1.3.1
        imagePullPolicy: Always

        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 2Gi

        env:
        - name: CLAMAV_ADDRESS
          value: localhost
        - name: TRUSTED_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: TRUSTED_SERVICE_URL
        - name: TRUSTED_SERVICE_GLOBAL_URL
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: TRUSTED_SERVICE_GLOBAL_URL
        - name: DEFAULT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: DOCUMENT_SERVICE_DEFAULT_SECRET_KEY
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: DOCUMENT_SERVICE_S3_ACCESS_KEY_ID
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: DOCUMENT_SERVICE_S3_ENDPOINT
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: DOCUMENT_SERVICE_S3_SECRET_ACCESS_KEY

        ports:
        - name: http
          containerPort: 8799
          protocol: TCP
        
        startupProbe:
          httpGet:
            path: /api/info
            port: http
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /api/info
            port: http
        readinessProbe:
          httpGet:
            path: /api/info
            port: http

      - name: clamav
        image: clamav/clamav:1.2
        imagePullPolicy: Always

        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 2Gi

        ports:
        - name: tcp
          containerPort: 3310
          protocol: TCP
        
        startupProbe:
          initialDelaySeconds: 60
          failureThreshold: 20
          periodSeconds: 30
          tcpSocket:
            port: tcp
        livenessProbe:
          initialDelaySeconds: 300
          tcpSocket:
            port: tcp
        readinessProbe:
          initialDelaySeconds: 90
          tcpSocket:
            port: tcp
