apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/safy/base

patches:

  - target:
      version: v1
      kind: Ingress
      name: safy-trusted-service-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: app.staging.bnetd.ci

  - target:
      version: v1
      kind: Ingress
      name: safy-trusted-service-global-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app-global.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: app-global.staging.bnetd.ci
      - op: replace
        path: /metadata/annotations/kubernetes.io~1ingress.class
        value: nginx
      - op: add
        path: "/metadata/annotations/nginx.ingress.kubernetes.io~1auth-tls-secret"
        value: default/ejbca-ca-secret
      - op: add
        path: "/metadata/annotations/nginx.ingress.kubernetes.io~1auth-tls-verify-client"
        value: 'on'

  - target:
      version: v1
      kind: Ingress
      name: safy-document-service-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: document.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: document.staging.bnetd.ci

  - target:
      version: v1
      kind: Deployment
      name: safy-trusted-service-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/safy-io/safy/safy-trusted-service:master
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: SERVER_URL
          value: https://app.staging.bnetd.ci/
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: GLOBAL_URL
          value: https://app-global.staging.bnetd.ci/
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: POSTGRESQL_HOST
          value: safy-postgres-cluster-1-cluster.cluster-cnue6eikcwxf.eu-west-1.rds.amazonaws.com
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: SMTP_SENDER_EMAIL
          value: no-reply@b
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: SMTP_SENDER_NAME
          value: Safy
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_REGION
          value: eu-west-1
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_ENDPOINT
          value: https://s3.eu-west-1.amazonaws.com
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_PERSISTENT_BUCKET
          value: safy-staging-safy-app
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_TEMP_BUCKET
          value: safy-staging-safy-temp
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: TIMESTAMP_POLICY_OID
          value: 1.3.6.1.4.1.60428.1.2.1.999

  - target:
      version: v1
      kind: Deployment
      name: safy-document-service-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/safy-io/safy/safy-document-service:master
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: SERVER_URL
          value: https://document.staging.bnetd.ci/
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: TRUSTED_SERVICE_URL
          value: https://app.staging.bnetd.ci/
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: TRUSTED_SERVICE_GLOBAL_URL
          value: https://app-global.staging.bnetd.ci/
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_REGION
          value: eu-west-1
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_ENDPOINT
          value: https://s3.eu-west-1.amazonaws.com
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_PERSISTENT_BUCKET
          value: safy-staging-safy-app
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_TEMP_BUCKET
          value: safy-staging-safy-temp
