apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../trusted-service
  - minio
  - cnpg-with-minio

patches:

  - target:
      version: v1
      kind: Deployment
      name: trusted-service-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: S3_ENDPOINT
          value: http://trusted-service-minio-service:9000
