apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ejbca-postgresql
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: ejbca_db
      owner: ejbca_user
  #   recovery:
  #     source: ejbca-postgresql
  #     recoveryTarget:
  #       targetTime: "2023-04-21 15:31:00+00:00"
  # externalClusters:
  #   - name: ejbca-postgresql
  #     barmanObjectStore:
  #       destinationPath: s3://app/pg-backup
  #       endpointURL: http://ejbca-minio-service:9000
  #       s3Credentials:
  #         accessKeyId:
  #           name: ejbca-vaultsecret
  #           key: S3_ACCESS_KEY_ID
  #         secretAccessKey:
  #           name: ejbca-vaultsecret
  #           key: S3_SECRET_ACCESS_KEY
  #       wal:
  #         compression: gzip
  #       data:
  #         compression: gzip
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://app/pg-backup
      endpointURL: http://ejbca-minio-service:9000
      s3Credentials:
        accessKeyId:
          name: ejbca-vaultsecret
          key: S3_ACCESS_KEY_ID
        secretAccessKey:
          name: ejbca-vaultsecret
          key: S3_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
