apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ejbca

patches:

  - target:
      version: v1
      kind: Ingress
      name: ejbca-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ejbca.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ejbca.staging.bnetd.ci
      - op: replace
        path: "/metadata/annotations/nginx.ingress.kubernetes.io~1auth-tls-secret"
        value: safy-staging/ejbca-ca-secret

  - target:
      version: v1
      kind: Ingress
      name: ejbca-ocsp-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: o-pki.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: o-pki.staging.bnetd.ci
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /bnetd-intermediate-ca-g1

  - target:
      version: v1
      kind: Ingress
      name: ejbca-root-crl-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: c-pki.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: c-pki.staging.bnetd.ci
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /bnetd-root-ca-g1.crl
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1configuration-snippet
        value: >
          rewrite ^/
          /ejbca/publicweb/crls/search.cgi?iHash=gH9inuHfOXvsF2MPghdJH0j4j%2Bw
          break;

  - target:
      version: v1
      kind: Ingress
      name: ejbca-intermediate-crl-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: c-pki.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: c-pki.staging.bnetd.ci
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /bnetd-intermediate-ca-g1.crl
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1configuration-snippet
        value: >
          rewrite ^/
          /ejbca/publicweb/crls/search.cgi?iHash=j3%2BThuwWdqqSB8IO2YJ9mIihHzk
          break;

  - target:
      version: v1
      kind: Ingress
      name: ejbca-root-cert-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: i-pki.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: i-pki.staging.bnetd.ci
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /bnetd-root-ca-g1.cer
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1configuration-snippet
        value: >
          rewrite ^/
          /ejbca/publicweb/webdist/certdist?cmd=iecacert&level=0&issuer=CN%3DBNETD+Root+CA+G1+%28staging%29%2CorganizationIdentifier%3DNTRCI-CI-ABJ-01-1994-B30-180858%2CO%3DBUREAU+NATIONAL+D%27ETUDES+TECHNIQUES+ET+DE+DEVELOPPEMENT%2CC%3DCI
          break;

  - target:
      version: v1
      kind: Ingress
      name: ejbca-intermediate-cert-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: i-pki.staging.bnetd.ci
      - op: replace
        path: /spec/tls/0/hosts/0
        value: i-pki.staging.bnetd.ci
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /bnetd-intermediate-ca-g1.cer
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1configuration-snippet
        value: >
          rewrite ^/
          /ejbca/publicweb/webdist/certdist?cmd=iecacert&level=0&issuer=CN%3DBNETD+Intermediate+CA+G1+%28staging%29%2CorganizationIdentifier%3DNTRCI-CI-ABJ-01-1994-B30-180858%2CO%3DBUREAU+NATIONAL+D%27ETUDES+TECHNIQUES+ET+DE+DEVELOPPEMENT%2CC%3DCI
          break;
