apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ejbca-vaultsecret
spec:
  keys:
    - PASSWORD_ENCRYPTION_KEY
    - S3_ACCESS_KEY_ID
    - S3_SECRET_ACCESS_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
  path: internal/ejbca/app-env
  type: Opaque
