apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ejbca-root-cert-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: >
      rewrite ^/
      /ejbca/publicweb/webdist/certdist?cmd=iecacert&level=0&issuer=CN%3DSafy+Root+CA+G1%2CorganizationIdentifier%3DNTRMA-135645%2CO%3DSAFY.io%2CC%3DMA
      break;
spec:
  tls:
    - hosts:
        - i.pki.bpsusine.com
      secretName: ejbca-issuer-cert
  rules:
    - host: i.pki.bpsusine.com
      http:
        paths:
          - path: /safy-root-ca.cer
            pathType: ImplementationSpecific
            backend:
              service:
                name: ejbca-service
                port:
                  name: proxied-https
