apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca-deployment
  labels:
    app: ejbca
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ejbca
  template:
    metadata:
      labels:
        app: ejbca
    spec:
      containers:
      - name: ejbca
        image: ghcr.io/safy-io/ejbca-ce:9.0.0
        imagePullPolicy: Always
        
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 2Gi
        
        ports:
        - containerPort: 8081
          name: proxied-http
        - containerPort: 8082
          name: proxied-https
        
        env:
        - name: PROXY_HTTP_BIND
          value: "0.0.0.0"
        - name: TLS_SETUP_ENABLED
          value: later
        - name: DATABASE_JDBC_URL
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: EJBCA_JDBC_URL
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: EJBCA_DB_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: EJBCA_DB_PASSWORD
        - name: PASSWORD_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: EJBCA_PASSWORD_ENCRYPTION_KEY        
        - name: SMTP_DESTINATION
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: SMTP_ADDRESS
        - name: SMTP_DESTINATION_PORT
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: SMTP_PORT
        - name: SMTP_SSL_ENABLED
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: SMTP_SSL
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: SMTP_PASSWORD
        - name: SMTP_FROM
          valueFrom:
            secretKeyRef:
              name: safy-vaultsecret
              key: EJBCA_SMTP_FROM_EMAIL

        startupProbe:
          httpGet:
            path: /ejbca/publicweb/healthcheck/ejbcahealth
            port: proxied-http
          timeoutSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /ejbca/publicweb/healthcheck/ejbcahealth
            port: proxied-http
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ejbca/publicweb/healthcheck/ejbcahealth
            port: proxied-http
          timeoutSeconds: 5
      
        volumeMounts: []

      volumes: []
